### ISSUE TITLE
ONE-bug

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/ampersand-models#1]
When compiling `\git\ampersand-models\NVWA DTV\Login.adl` and running it on XAMPP, I get a database error.

![image](https://cloud.githubusercontent.com/assets/275768/7466963/6a1a793a-f2ee-11e4-8165-a1d11e3de177.png)

Symptoms:
The Ampersand programmer can fix the problem by removing `V[ONE*SESSION];` from line 128 of `Login.adl`, which is the root expression of `INTERFACE "Wijzig uw account"`. Obviously, the mistake is to use `ONE` as the session atom. Nevertheless, Ampersand should not respond with a database error, but rather with an Ampersand message about `ONE`.

Identification:
This concerns commit d503b15, which has been compiled with Ampersand v3.1.0[master:c76fb54], build time: 04-May-15 16:34:24 West-Europa, by the following command: 
`D:>Ampersand --verbose --newFrontend -pD:\htdocs\klad\ Login.adl`

**Comment by Michiel-s** [comment]
Het was wat uitzoek werk, maar ik denk dat het probleem in de normalizer zit. Het is als volgt:

In Generics.php zitten 2 array die hier relevant zijn:
1) De $allConcepts array
2) De $tableColumnInfo array

In bovengenoemd ADL script zit zowel een Interface met start expressie `V[ONE*SESSION];...` als `I[ONE]`

De laatst genoemde defintie, zorgt ervoor dat het ONE concept wel wordt opgenomen in de $allConcepts array (het framework kan het concept dus gewoon vinden), maar niet in de $tablleColumInfo array (er is geen tabel voor ONE aangemaakt). Logischerwijs komt er dus een database gerelateerde fout.

Als je echter alleen interfaces met V[ONE*Iets] hebt, dan wordt echter het concept ONE niet in de $allConcepts array gezet en krijg je een andere fout (nl. "Concept ONE does not exists in allConcepts"). Vandaar dat ik een andere foutmelding dan jij kreeg Stef.

Dit lijkt me geen consistent gedrag.

Ik zal iig de foutmelding vanuit php wat verduidelijken, maar verder is het meer een Haskell dingetje.

**Comment by hanjoosten** [comment]
@stefjoosten Op Github kan je per repository een issuelijst hebben. Dit issue heb je aangemaakt in de repo van Ampersand-models. Dat is niet handig. Graag niet meer doen!  De issue lijst van ampersand is bij de ampersand repository. Dan houden we alles gezellig bij elkaar.
